const COLORS = {
  PRIMARY_START: '#f18a69',
  PRIMARY_END: '#d13e60',
  LIGHT_WHITE: '#fcefe9',
  INPUT_PLACEHOLDER: '#f1a895',
  LIGHTER_WHITE: '#f4e4e2',
  CIRCLE_INACTIVE: '#ecbfbe',
  CIRCLE_ACTIVE: '#90ee90',
  ITEM_LIST_TEXT: '#555555',
  ITEM_LIST_TEXT_STRIKE: '#c4c4cc',
  DELETE_ICON_COLOR: '#bc2e4c'
}

export default COLORS;
